<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_HotConnect2" Id="{edf59865-9bbd-4e75-9a19-f5cf1e484e54}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HotConnect2
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>