<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_HotConnect1" Id="{48b39ecc-80ef-409d-9886-ccd24b836350}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HotConnect1 IMPLEMENTS I_ControlScheme
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fbDecline1			: FB_DeclineNcConveyer;
	fbShortStraight1	: FB_SsNcConveyer;
	fbInline1			: FB_InclineNcConveyer;
END_VAR
VAR_IN_OUT
	Axis1	: AXIS_REF;
	Axis2	: AXIS_REF;
	Axis3	: AXIS_REF;
	Axis4	: AXIS_REF;
	Axis5	: AXIS_REF;
	Axis6	: AXIS_REF;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>